/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package cheeseslicer;

import java.io.File;

public class App {
    
    public static void main(String[] args) {
        
        if (args.length < 2) {
            System.err.println("Please Input A File.");
            return;
        }

    }

}
